### PR TITLE
SUPESC-200: Braintree Credit Card doesn't work with Apostrophe

### PR DESCRIPTION
**Pull request by dmiseev**
- Developer(s): @dmiseev

- Ticket: https://spryker.atlassian.net/browse/SUPESC-200

#### Documentation

- [ ] Functional documentation provided or in progress?
- [ ] Integration guide for projects provided or not needed?
- [ ] Migration guides for all contained majors provided or not needed?

#### Release Table

   Module                | Release Type         | Constraint Updates         |
   :--------------------- | :------------------------ | :--------------------- |
   Braintree             | patch                 |                       |

-----------------------------------------

##### Change log

Fixes

- Adjusted `CreditCardSubForm` in order to convert billing `firstName` and `lastName` to ASCII format.

### CODE REVIEW

**Review by aleksey-kotsuba — COMMENTED** [review]
Looks good. @dereuromark  asked to raise phpstan level at least to 7.
@dmiseev please check if it's possible

**Comment by dereuromark** [comment]
There should be test cases added specifically for e.g. German handling of this:

Herr Müßig is expected to be `Muessig` IMO, not `Musig` or alike.

**Comment by dmiseev** [comment]
We have `17 errors` for 5 level, I guess it will painful to increase it.
@aleksey-kotsuba

**Comment by aleksey-kotsuba** [comment]
@dereuromark it will be hard to update module to phpstan lvl 7. I think it should be processed as separate ticket and added to the further scope.

**Review by aleksey-kotsuba — APPROVED** [review]

**Pull request merged**
